//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.PaymentManger {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultCodeField;
        
        private string faultStringField;
        
        private System.DateTime timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                this.faultStringField = value;
                this.RaisePropertyChanged("faultString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class BankBusinessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class InitiatePaymentTransactionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abRefNumField;
        
        private string merchantRefNumField;
        
        private string ibURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string abRefNum {
            get {
                return this.abRefNumField;
            }
            set {
                this.abRefNumField = value;
                this.RaisePropertyChanged("abRefNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string merchantRefNum {
            get {
                return this.merchantRefNumField;
            }
            set {
                this.merchantRefNumField = value;
                this.RaisePropertyChanged("merchantRefNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ibURL {
            get {
                return this.ibURLField;
            }
            set {
                this.ibURLField = value;
                this.RaisePropertyChanged("ibURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class InitiatePaymentDetailsReply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InitiatePaymentTransactionDetails initiatePaymentTransactionDetailsField;
        
        private string responseCodeField;
        
        private BankBusinessException bankBusinessExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InitiatePaymentTransactionDetails initiatePaymentTransactionDetails {
            get {
                return this.initiatePaymentTransactionDetailsField;
            }
            set {
                this.initiatePaymentTransactionDetailsField = value;
                this.RaisePropertyChanged("initiatePaymentTransactionDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BankBusinessException bankBusinessException {
            get {
                return this.bankBusinessExceptionField;
            }
            set {
                this.bankBusinessExceptionField = value;
                this.RaisePropertyChanged("bankBusinessException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class Merchant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long merchantIdField;
        
        private string merchantRefNumField;
        
        private double paymentAmountField;
        
        private string paymentCurrencyField;
        
        private int merchantTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("merchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string merchantRefNum {
            get {
                return this.merchantRefNumField;
            }
            set {
                this.merchantRefNumField = value;
                this.RaisePropertyChanged("merchantRefNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double paymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
                this.RaisePropertyChanged("paymentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string paymentCurrency {
            get {
                return this.paymentCurrencyField;
            }
            set {
                this.paymentCurrencyField = value;
                this.RaisePropertyChanged("paymentCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int merchantType {
            get {
                return this.merchantTypeField;
            }
            set {
                this.merchantTypeField = value;
                this.RaisePropertyChanged("merchantType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class InitiatePaymentDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double transactionAmountField;
        
        private string olpIdAliasField;
        
        private string merchantRefNumField;
        
        private Merchant[] merchantsField;
        
        private long merchantIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double transactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
                this.RaisePropertyChanged("transactionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string olpIdAlias {
            get {
                return this.olpIdAliasField;
            }
            set {
                this.olpIdAliasField = value;
                this.RaisePropertyChanged("olpIdAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string merchantRefNum {
            get {
                return this.merchantRefNumField;
            }
            set {
                this.merchantRefNumField = value;
                this.RaisePropertyChanged("merchantRefNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchants", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Merchant[] merchants {
            get {
                return this.merchantsField;
            }
            set {
                this.merchantsField = value;
                this.RaisePropertyChanged("merchants");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("merchantId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", ConfigurationName="PaymentManger.BAJPaymentManager")]
    public interface BAJPaymentManager {
        
        // CODEGEN: Generating message contract since message InitiatePaymentDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="InitiatePaymentDetails", ReplyAction="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1/BAJPa" +
            "ymentManager/InitiatePaymentDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lib.PaymentManger.Fault), Action="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1/BAJPa" +
            "ymentManager/InitiatePaymentDetails/Fault/Fault", Name="Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lib.PaymentManger.InitiatePaymentDetailsResponse InitiatePaymentDetails(Lib.PaymentManger.InitiatePaymentDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="InitiatePaymentDetails", ReplyAction="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1/BAJPa" +
            "ymentManager/InitiatePaymentDetailsResponse")]
        System.Threading.Tasks.Task<Lib.PaymentManger.InitiatePaymentDetailsResponse> InitiatePaymentDetailsAsync(Lib.PaymentManger.InitiatePaymentDetailsRequest1 request);
        
        // CODEGEN: Generating message contract since message ConfirmPaymentDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="ConfirmPaymentDetails", ReplyAction="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1/BAJPa" +
            "ymentManager/ConfirmPaymentDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lib.PaymentManger.Fault), Action="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1/BAJPa" +
            "ymentManager/ConfirmPaymentDetails/Fault/Fault", Name="Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lib.PaymentManger.ConfirmPaymentDetailsResponse ConfirmPaymentDetails(Lib.PaymentManger.ConfirmPaymentDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConfirmPaymentDetails", ReplyAction="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1/BAJPa" +
            "ymentManager/ConfirmPaymentDetailsResponse")]
        System.Threading.Tasks.Task<Lib.PaymentManger.ConfirmPaymentDetailsResponse> ConfirmPaymentDetailsAsync(Lib.PaymentManger.ConfirmPaymentDetailsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enterprise.olp.baj.com.sa/Infrastructure/BAJEnterpriseContext")]
    public partial class BAJEnterpriseContext_Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContextInfo contextInfoField;
        
        private RequestOriginator requestOriginatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ContextInfo contextInfo {
            get {
                return this.contextInfoField;
            }
            set {
                this.contextInfoField = value;
                this.RaisePropertyChanged("contextInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RequestOriginator requestOriginator {
            get {
                return this.requestOriginatorField;
            }
            set {
                this.requestOriginatorField = value;
                this.RaisePropertyChanged("requestOriginator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enterprise.olp.baj.com.sa/Infrastructure/BAJEnterpriseContext")]
    public partial class ContextInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string processContextIdField;
        
        private string businessContextIdField;
        
        private int applicationContextIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProcessContextId {
            get {
                return this.processContextIdField;
            }
            set {
                this.processContextIdField = value;
                this.RaisePropertyChanged("ProcessContextId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string businessContextId {
            get {
                return this.businessContextIdField;
            }
            set {
                this.businessContextIdField = value;
                this.RaisePropertyChanged("businessContextId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int applicationContextId {
            get {
                return this.applicationContextIdField;
            }
            set {
                this.applicationContextIdField = value;
                this.RaisePropertyChanged("applicationContextId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enterprise.olp.baj.com.sa/Infrastructure/BAJEnterpriseContext")]
    public partial class RequestOriginator : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requesterCodeField;
        
        private string machineIPAddressField;
        
        private string userPrincipleNameField;
        
        private System.DateTime requestedTimestampField;
        
        private int channelIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requesterCode {
            get {
                return this.requesterCodeField;
            }
            set {
                this.requesterCodeField = value;
                this.RaisePropertyChanged("requesterCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string machineIPAddress {
            get {
                return this.machineIPAddressField;
            }
            set {
                this.machineIPAddressField = value;
                this.RaisePropertyChanged("machineIPAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userPrincipleName {
            get {
                return this.userPrincipleNameField;
            }
            set {
                this.userPrincipleNameField = value;
                this.RaisePropertyChanged("userPrincipleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime requestedTimestamp {
            get {
                return this.requestedTimestampField;
            }
            set {
                this.requestedTimestampField = value;
                this.RaisePropertyChanged("requestedTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int channelId {
            get {
                return this.channelIdField;
            }
            set {
                this.channelIdField = value;
                this.RaisePropertyChanged("channelId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitiatePaymentDetails", WrapperNamespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", IsWrapped=true)]
    public partial class InitiatePaymentDetailsRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://enterprise.olp.baj.com.sa/Infrastructure/BAJEnterpriseContext")]
        public Lib.PaymentManger.BAJEnterpriseContext_Type enterpriseContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Lib.PaymentManger.InitiatePaymentDetailsRequest InitiatePaymentDetailsRequest;
        
        public InitiatePaymentDetailsRequest1() {
        }
        
        public InitiatePaymentDetailsRequest1(Lib.PaymentManger.BAJEnterpriseContext_Type enterpriseContext, Lib.PaymentManger.InitiatePaymentDetailsRequest InitiatePaymentDetailsRequest) {
            this.enterpriseContext = enterpriseContext;
            this.InitiatePaymentDetailsRequest = InitiatePaymentDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitiatePaymentDetailsResponse", WrapperNamespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", IsWrapped=true)]
    public partial class InitiatePaymentDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Lib.PaymentManger.InitiatePaymentDetailsReply InitiatePaymentDetailsReply;
        
        public InitiatePaymentDetailsResponse() {
        }
        
        public InitiatePaymentDetailsResponse(Lib.PaymentManger.InitiatePaymentDetailsReply InitiatePaymentDetailsReply) {
            this.InitiatePaymentDetailsReply = InitiatePaymentDetailsReply;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class ConfirmPaymentDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdEncField;
        
        private long merchantIdField;
        
        private string merchantRefNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string transactionIdEnc {
            get {
                return this.transactionIdEncField;
            }
            set {
                this.transactionIdEncField = value;
                this.RaisePropertyChanged("transactionIdEnc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("merchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string merchantRefNum {
            get {
                return this.merchantRefNumField;
            }
            set {
                this.merchantRefNumField = value;
                this.RaisePropertyChanged("merchantRefNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class ConfirmPaymentDetailsReply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConfirmPaymentTransactionDetails confirmPaymentTransactionDetailsField;
        
        private string responseCodeField;
        
        private BankBusinessException bankBusinessExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ConfirmPaymentTransactionDetails ConfirmPaymentTransactionDetails {
            get {
                return this.confirmPaymentTransactionDetailsField;
            }
            set {
                this.confirmPaymentTransactionDetailsField = value;
                this.RaisePropertyChanged("ConfirmPaymentTransactionDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BankBusinessException bankBusinessException {
            get {
                return this.bankBusinessExceptionField;
            }
            set {
                this.bankBusinessExceptionField = value;
                this.RaisePropertyChanged("bankBusinessException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1")]
    public partial class ConfirmPaymentTransactionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abRefNumField;
        
        private string merchantRefNumField;
        
        private int paymentStatusField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string abRefNum {
            get {
                return this.abRefNumField;
            }
            set {
                this.abRefNumField = value;
                this.RaisePropertyChanged("abRefNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string merchantRefNum {
            get {
                return this.merchantRefNumField;
            }
            set {
                this.merchantRefNumField = value;
                this.RaisePropertyChanged("merchantRefNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int paymentStatus {
            get {
                return this.paymentStatusField;
            }
            set {
                this.paymentStatusField = value;
                this.RaisePropertyChanged("paymentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmPaymentDetails", WrapperNamespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", IsWrapped=true)]
    public partial class ConfirmPaymentDetailsRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://enterprise.olp.baj.com.sa/Infrastructure/BAJEnterpriseContext")]
        public Lib.PaymentManger.BAJEnterpriseContext_Type enterpriseContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Lib.PaymentManger.ConfirmPaymentDetailsRequest ConfirmPaymentDetailsRequest;
        
        public ConfirmPaymentDetailsRequest1() {
        }
        
        public ConfirmPaymentDetailsRequest1(Lib.PaymentManger.BAJEnterpriseContext_Type enterpriseContext, Lib.PaymentManger.ConfirmPaymentDetailsRequest ConfirmPaymentDetailsRequest) {
            this.enterpriseContext = enterpriseContext;
            this.ConfirmPaymentDetailsRequest = ConfirmPaymentDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmPaymentDetailsResponse", WrapperNamespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", IsWrapped=true)]
    public partial class ConfirmPaymentDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://olp.baj.com.sa/bajpaymentmanagement/service/bajpaymentmanager/intf/1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Lib.PaymentManger.ConfirmPaymentDetailsReply ConfirmPaymentDetailsReply;
        
        public ConfirmPaymentDetailsResponse() {
        }
        
        public ConfirmPaymentDetailsResponse(Lib.PaymentManger.ConfirmPaymentDetailsReply ConfirmPaymentDetailsReply) {
            this.ConfirmPaymentDetailsReply = ConfirmPaymentDetailsReply;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BAJPaymentManagerChannel : Lib.PaymentManger.BAJPaymentManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BAJPaymentManagerClient : System.ServiceModel.ClientBase<Lib.PaymentManger.BAJPaymentManager>, Lib.PaymentManger.BAJPaymentManager {
        
        public BAJPaymentManagerClient() {
        }
        
        public BAJPaymentManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BAJPaymentManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BAJPaymentManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BAJPaymentManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lib.PaymentManger.InitiatePaymentDetailsResponse Lib.PaymentManger.BAJPaymentManager.InitiatePaymentDetails(Lib.PaymentManger.InitiatePaymentDetailsRequest1 request) {
            return base.Channel.InitiatePaymentDetails(request);
        }
        
        public Lib.PaymentManger.InitiatePaymentDetailsReply InitiatePaymentDetails(Lib.PaymentManger.BAJEnterpriseContext_Type enterpriseContext, Lib.PaymentManger.InitiatePaymentDetailsRequest InitiatePaymentDetailsRequest) {
            Lib.PaymentManger.InitiatePaymentDetailsRequest1 inValue = new Lib.PaymentManger.InitiatePaymentDetailsRequest1();
            inValue.enterpriseContext = enterpriseContext;
            inValue.InitiatePaymentDetailsRequest = InitiatePaymentDetailsRequest;
            Lib.PaymentManger.InitiatePaymentDetailsResponse retVal = ((Lib.PaymentManger.BAJPaymentManager)(this)).InitiatePaymentDetails(inValue);
            return retVal.InitiatePaymentDetailsReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lib.PaymentManger.InitiatePaymentDetailsResponse> Lib.PaymentManger.BAJPaymentManager.InitiatePaymentDetailsAsync(Lib.PaymentManger.InitiatePaymentDetailsRequest1 request) {
            return base.Channel.InitiatePaymentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lib.PaymentManger.InitiatePaymentDetailsResponse> InitiatePaymentDetailsAsync(Lib.PaymentManger.BAJEnterpriseContext_Type enterpriseContext, Lib.PaymentManger.InitiatePaymentDetailsRequest InitiatePaymentDetailsRequest) {
            Lib.PaymentManger.InitiatePaymentDetailsRequest1 inValue = new Lib.PaymentManger.InitiatePaymentDetailsRequest1();
            inValue.enterpriseContext = enterpriseContext;
            inValue.InitiatePaymentDetailsRequest = InitiatePaymentDetailsRequest;
            return ((Lib.PaymentManger.BAJPaymentManager)(this)).InitiatePaymentDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lib.PaymentManger.ConfirmPaymentDetailsResponse Lib.PaymentManger.BAJPaymentManager.ConfirmPaymentDetails(Lib.PaymentManger.ConfirmPaymentDetailsRequest1 request) {
            return base.Channel.ConfirmPaymentDetails(request);
        }
        
        public Lib.PaymentManger.ConfirmPaymentDetailsReply ConfirmPaymentDetails(Lib.PaymentManger.BAJEnterpriseContext_Type enterpriseContext, Lib.PaymentManger.ConfirmPaymentDetailsRequest ConfirmPaymentDetailsRequest) {
            Lib.PaymentManger.ConfirmPaymentDetailsRequest1 inValue = new Lib.PaymentManger.ConfirmPaymentDetailsRequest1();
            inValue.enterpriseContext = enterpriseContext;
            inValue.ConfirmPaymentDetailsRequest = ConfirmPaymentDetailsRequest;
            Lib.PaymentManger.ConfirmPaymentDetailsResponse retVal = ((Lib.PaymentManger.BAJPaymentManager)(this)).ConfirmPaymentDetails(inValue);
            return retVal.ConfirmPaymentDetailsReply;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lib.PaymentManger.ConfirmPaymentDetailsResponse> Lib.PaymentManger.BAJPaymentManager.ConfirmPaymentDetailsAsync(Lib.PaymentManger.ConfirmPaymentDetailsRequest1 request) {
            return base.Channel.ConfirmPaymentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lib.PaymentManger.ConfirmPaymentDetailsResponse> ConfirmPaymentDetailsAsync(Lib.PaymentManger.BAJEnterpriseContext_Type enterpriseContext, Lib.PaymentManger.ConfirmPaymentDetailsRequest ConfirmPaymentDetailsRequest) {
            Lib.PaymentManger.ConfirmPaymentDetailsRequest1 inValue = new Lib.PaymentManger.ConfirmPaymentDetailsRequest1();
            inValue.enterpriseContext = enterpriseContext;
            inValue.ConfirmPaymentDetailsRequest = ConfirmPaymentDetailsRequest;
            return ((Lib.PaymentManger.BAJPaymentManager)(this)).ConfirmPaymentDetailsAsync(inValue);
        }
    }
}
